### PR TITLE
Add support of namespaces as cache key

### PR DESCRIPTION
**Pull request by shaffe-fr**
Add FNM_NOESCAPE to disable backslash escaping.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test to this PR?

**Comment by shaffe-fr** [comment]
Hi, I added some tests to the initial commit.

**Comment by peter279k** [comment]
Hi @shaffe-fr, the `StyleCI` is failed due to failed coding style check.

Can you fix that? Thanks.

**Comment by shaffe-fr** [comment]
OK, I'll check that, 
I thought the issue was caused by the CI configuration: 
>Config Issue
>The provided config option 'linting' was not valid.

**Comment by shaffe-fr** [comment]
The error was caused by a change in styleci API : https://docs.styleci.io/change-log.
I added a commit to remove the deprecated linting option.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
